// Code generated by Slice Machine. DO NOT EDIT.

import HeroCarouselSlice from './HeroCarouselSlice'
import HomePageProductsSlice from './HomePageProductsSlice'
import LargePromoBlockSlice from './LargePromoBlockSlice'
import SmallBannerSlice from './SmallBannerSlice'
import SmallPromoBlockSlice from './SmallPromoBlockSlice'

export {
  HeroCarouselSlice,
  HomePageProductsSlice,
  LargePromoBlockSlice,
  SmallBannerSlice,
  SmallPromoBlockSlice,
}

export const components = {
  hero_carousel_slice: HeroCarouselSlice,
  home_page_products_slice: HomePageProductsSlice,
  large_promo_block_slice: LargePromoBlockSlice,
  small_banner_slice: SmallBannerSlice,
  small_promo_block_slice: SmallPromoBlockSlice,
}
